"use client";

import { ArrowRight, Bell, CalendarDays, CheckCheck, Clock3, MapPin, Plus, Repeat2, Ticket, TrainFront } from "lucide-react";
import { addDays, bookingDay, formatDay, type Journey, type Planner } from "@/lib/travel-planner";
import type { DashboardView } from "@/lib/planning-views";

import { STATUS } from "./forms";
import s from "./planner.module.css";

/** Renders actionable journey metrics, booking deadlines, and upcoming travel. */
export function Dashboard({ planner, today, data, openJourney, createJourney, go, chooseDate }: { planner: Planner; today: string; data: DashboardView; openJourney: (j: Journey) => void; createJourney: () => void; go: (tab: "journeys" | "calendar" | "routines" | "holidays", status?: Journey["status"]) => void; chooseDate: (date: string) => void }) {
  const {upcoming,bookingSoon,totals,week}=data;
  const attention=data.attention.map(j=>({j,label:j.status==="cancellation_needed"?"Cancellation To Confirm":"Booking Is Open"}));
  const holidays = planner.holidays.filter(h => h.date >= today).sort((a,b) => a.date.localeCompare(b.date)).slice(0,3);
  const total=totals.upcoming,overviewTotal=totals.booked+totals.ready+totals.toCancel;
  const overview={booked:totals.booked,toBook:totals.ready,toCancel:totals.toCancel,total:overviewTotal,bookedPercent:overviewTotal?Math.round(totals.booked/overviewTotal*100):0,bookedAngle:overviewTotal?totals.booked/overviewTotal*100:0,toBookAngle:overviewTotal?(totals.booked+totals.ready)/overviewTotal*100:0};
  return <div className={s.dashboard}>
    <div className={s.metricGrid}>
      {[{label:"Ready To Book",value:totals.ready,hint:"Booking windows are open",icon:Bell,tone:"purple"}, {label:"Tickets Booked",value:totals.booked,hint:"For upcoming journeys",icon:Ticket,tone:"mint"}, {label:"Completed Journeys",value:totals.completed,hint:"Available in your history",icon:CheckCheck,tone:"pink"}, {label:"Tickets To Cancel",value:overview.toCancel,hint:"Cancellation needs confirmation",icon:Ticket,tone:"amber"}].map(m => <button key={m.label} className={s.metricCard} onClick={() => go("journeys", m.label === "Completed Journeys" ? "completed" : m.label === "Tickets To Cancel" ? "cancellation_needed" : m.label === "Tickets Booked" ? "booked" : "needs_booking")}><div><span className={`${s.metricIcon} ${s[m.tone]}`}><m.icon size={21}/></span><span className={s.metricLabel}>{m.label}</span></div><strong>{m.value}</strong><small>{m.hint}</small></button>)}
    </div>
    <div className={s.dashboardGrid}>
      <section className={s.dashboardPanel}><header><div><span className={s.eyebrow}>Your next steps</span><h2>Needs Attention <span>{totals.attention}</span></h2></div><button className={s.textButton} onClick={() => go("journeys")}>{totals.attention>attention.length?"View all journeys":"View journeys"} <ArrowRight size={15}/></button></header>
        {attention.length ? <div className={`${s.dashboardList} ${s.attentionList}`}>{attention.map(({j,label}) => <button key={`${j.id}-${label}`} className={s.dashboardRow} onClick={() => openJourney(j)}><span className={s.dateTile}><b>{j.date.slice(-2)}</b><small>{formatDay(j.date,{month:"short"})}</small></span><div><b>{j.from} <ArrowRight size={13}/> {j.to}</b><small>{label}</small></div><Chevron /></button>)}</div> : <div className={s.dashboardEmpty}><CheckCheck size={26}/><h3>You’re All Caught Up</h3><p>{total ? "No bookings or cancellations need attention right now." : "Add a journey or routine to see your next booking dates here."}</p><button className={s.textButton} onClick={createJourney}><Plus size={15}/>Plan a journey</button></div>}
      </section>
      <section className={s.dashboardPanel}><header><div><span className={s.eyebrow}>Plan ahead</span><h2>Next Booking Openings</h2></div><Clock3 size={20}/></header><div className={s.dashboardList}>{bookingSoon.slice(0,4).map(j => <button className={s.dashboardRow} key={j.id} onClick={() => openJourney(j)}><span className={s.dateTile}><b>{bookingDay(j).slice(-2)}</b><small>{formatDay(bookingDay(j),{month:"short"})}</small></span><div><b>{j.from} <ArrowRight size={13}/> {j.to}</b><small>Travel · {formatDay(j.date,{day:"numeric",month:"short",year:"numeric"})}</small></div><Chevron/></button>)}{!bookingSoon.length && <p className={s.panelEmpty}>No future booking openings. Add a journey or check the journeys ready to book.</p>}</div></section>
      <section className={s.dashboardPanel}><header><div><span className={s.eyebrow}>On the horizon</span><h2>Upcoming Journeys</h2></div><TrainFront size={20}/></header><div className={s.dashboardList}>{upcoming.slice(0,4).map(j => <button className={s.dashboardRow} key={j.id} onClick={() => openJourney(j)}><span className={s.dateTile}><b>{j.date.slice(-2)}</b><small>{formatDay(j.date,{month:"short"})}</small></span><div><b>{j.from} <ArrowRight size={13}/> {j.to}</b><small>{formatDay(j.date,{weekday:"long"})} · {STATUS[j.status]}</small></div><Chevron/></button>)}{!upcoming.length && <p className={s.panelEmpty}>Your upcoming journeys will appear here.</p>}</div></section>
      <section className={s.dashboardPanel}><header><div><span className={s.eyebrow}>Travel overview</span><h2>Your Plans At A Glance</h2></div><CalendarDays size={20}/></header><div className={s.progressOverview}><div className={s.progressRing} role="img" aria-label={`Booking Status: ${overview.booked} Booked, ${overview.toBook} To Book, ${overview.toCancel} To Cancel`} style={{background:overview.total?`conic-gradient(var(--mint) 0 ${overview.bookedAngle}%, var(--purple) ${overview.bookedAngle}% ${overview.toBookAngle}%, var(--amber) ${overview.toBookAngle}% 100%)`:"var(--line)"}}><div><strong>{overview.bookedPercent}%</strong><small>booked</small></div></div><div className={s.progressLegend}><p><i className={s.green}/><span>Booked</span><b>{overview.booked}</b></p><p><i className={s.purple}/><span>To Book</span><b>{overview.toBook}</b></p><p><i className={s.amber}/><span>To Cancel</span><b>{overview.toCancel}</b></p></div></div><p className={s.help}>Booked, ready to book and cancellation-pending journeys. Future booking windows are excluded.</p><button className={s.dashboardLink} onClick={() => go("calendar")}>Open your calendar <ArrowRight size={16}/></button></section>
    </div>
    <section className={s.weekPanel}><header><div><span className={s.eyebrow}>The next seven days</span><h2>Your Travel Week</h2></div><button className={s.textButton} onClick={() => go("calendar")}>View calendar <ArrowRight size={15}/></button></header><div className={s.weekGrid}>{Array.from({length:7},(_,i)=>{const date=addDays(today,i);const count=week[date]?.journeys??0;const openings=week[date]?.bookings??0;const cancellations=week[date]?.cancellations??0;const off=planner.holidays.filter(h=>h.date===date);return <button key={date} className={`${s.weekDay} ${i===0?s.weekToday:""}`} onClick={()=>chooseDate(date)}><small>{i===0?"Today":formatDay(date,{weekday:"short"})}</small><b>{Number(date.slice(-2))}</b><span>{count?`${count} ${count===1?"journey":"journeys"}`:cancellations?`${cancellations} cancellation${cancellations===1?"":"s"} pending`:openings?`${openings} booking ${openings===1?"opening":"openings"}`:off.length?"Time off":"No plans"}</span>{count>0&&openings>0&&<small>{openings} booking {openings===1?"opening":"openings"}</small>}</button>;})}</div></section>
    <div className={s.dashboardBottom}><section className={s.dashboardPanel}><header><div><span className={s.eyebrow}>Make room for a break</span><h2>Upcoming Time Off</h2></div><button className={s.textButton} onClick={()=>go("holidays")}>View all <ArrowRight size={15}/></button></header>{holidays.map(h=><div className={s.timeOffRow} key={h.id}><MapPin size={17}/><div><b>{h.name}</b><small>{h.type==="company"?"Company holiday":"Personal leave"}</small></div><span>{formatDay(h.date)}</span></div>)}{!holidays.length&&<p className={s.panelEmpty}>Add your company holidays or personal leave to plan ahead.</p>}</section><section className={`${s.dashboardPanel} ${s.routineCallout}`}><span className={s.metricIcon}><Repeat2 size={24}/></span><h2>Give Regular Travel A Routine</h2><p>{planner.rules.length?`${planner.rules.filter(r=>!r.paused).length} active routines keep your travel plans up to date.`:"Choose your route and schedule once. We’ll create your upcoming journeys."}</p><button className={s.secondary} onClick={()=>go("routines")}>Manage routines <ArrowRight size={15}/></button></section></div>
  </div>;
}
/** Renders the shared forward navigation indicator. */
function Chevron(){return <ArrowRight className={s.rowArrow} size={16}/>;}
