"use client";
import {useSyncExternalStore, type ReactNode} from "react";
import Link from "next/link";
import {ArrowRight,CalendarDays,Files,House,LayoutList,Settings2} from "lucide-react";
import {addDays,bookingDay,formatDay,recurrenceLabel,type Journey,type TicketAttachment,type Planner,type Rule} from "@/lib/travel-planner";
import {groupTimeOff,stationLabel} from "@/lib/journey-display";
import type {DashboardView} from "@/lib/planning-views";
import {STATUS} from "./forms";
import {ActionMenu} from "./action-menu";
import m from "./mobile-workspace.module.css";

/** Observes the phone layout without changing the server-rendered desktop snapshot. */
function subscribe(listener:()=>void){const query=window.matchMedia("(max-width: 768px)");query.addEventListener("change",listener);return()=>query.removeEventListener("change",listener);}
/** Uses a separate phone presentation while retaining the shared account controller. */
export function useMobileWorkspace(){return useSyncExternalStore(subscribe,()=>window.matchMedia("(max-width: 768px)").matches,()=>false);}

/** Keeps primary destinations within thumb reach; other routes live in More. */
export function MobileNavigation({tab,more,openMore,navigate,disabled=false}:{tab:string;more:boolean;disabled?:boolean;openMore:()=>void;navigate:()=>void}){
  return <nav className={m.navigation} aria-label="Mobile navigation" inert={disabled}>{[{id:"home",label:"Home",href:"/",icon:House},{id:"journeys",label:"Journeys",href:"/journeys",icon:LayoutList},{id:"vault",label:"Tickets",href:"/tickets",icon:Files}].map(item=><Link key={item.id} href={item.href} aria-current={!more&&tab===item.id?"page":undefined} onClick={navigate}><item.icon size={21}/><span>{item.label}</span></Link>)}<button onClick={openMore} aria-expanded={more} aria-pressed={more||!["home","journeys","vault"].includes(tab)}><Settings2 size={21}/><span>More</span></button></nav>;
}
/** Presents one compact journey with a date tile and accessible whole-row action. */
export function MobileJourneyRow({journey:j,open,label,accessibleLabel,booking=false}:{journey:Journey;open:()=>void;label?:string;accessibleLabel?:string;booking?:boolean}){
  const date=booking?bookingDay(j):j.date;
  return <button className={m.row} onClick={open} aria-label={accessibleLabel??`Open journey ${j.from} to ${j.to}`}><span className={m.date}><b>{formatDay(date,{day:"2-digit"})}</b><small>{formatDay(date,{month:"short"})}</small></span><span className={m.rowText}><strong>{stationLabel(j.from)} <ArrowRight size={14}/> {stationLabel(j.to)}</strong><small>{label??(booking?`Booking opens · Travel ${formatDay(j.date)}`:`${formatDay(j.date,{weekday:"short",day:"numeric",month:"short",year:"numeric"})}${j.departureConfirmed&&j.departure?` · ${j.departure} IST`:""}`)}</small></span><ArrowRight size={17}/></button>;
}
/** Gives the next trip and pending actions priority over aggregate dashboard panels. */
export function MobileHome({data,open,view,plan,go}:{data:DashboardView;open:(j:Journey)=>void;view:(file:TicketAttachment)=>void;plan:()=>void;go:(status:string)=>void}){
  const next=data.upcoming.find(j=>j.status==="booked")??data.upcoming[0];
  const pdf=next?.attachments?.find(file=>file.type==="application/pdf");
  return <div className={m.screen}><h1>Your next trip</h1>{next?<section className={m.trip}><button className={m.tripOpen} onClick={()=>open(next)} aria-label={`Open journey ${next.from} to ${next.to}`}><span className={m.eyebrow}>{formatDay(next.date,{weekday:"long",day:"numeric",month:"long"})}{next.departureConfirmed&&next.departure?` · ${next.departure} IST`:""}</span><span className={m.route}><b>{stationLabel(next.from)}</b><ArrowRight size={22}/><b>{stationLabel(next.to)}</b></span><span className={m.fullRoute}>{next.from} → {next.to}</span><span className={m.tripDetails}>{[next.trainNumber,next.trainName||next.train,next.coach&&`Coach ${next.coach}`,next.seat&&`Seat ${next.seat}`].filter(Boolean).join(" · ")||STATUS[next.status]}</span></button>{pdf&&<button className={m.primary} onClick={()=>view(pdf)}><Files size={17}/>View ticket</button>}</section>:<section className={m.empty}><CalendarDays size={26}/><h2>No upcoming trip yet</h2><p>Your next booked journey will appear here.</p></section>}<div className={m.actions}><button onClick={()=>go("needs_booking")}><b>{data.totals.ready}</b><span>Ready to book</span><ArrowRight size={16}/></button><button onClick={()=>go("cancellation_needed")}><b>{data.totals.toCancel}</b><span>To cancel</span><ArrowRight size={16}/></button></div>{data.attention.length>0&&<section><div className={m.sectionHead}><h2>Needs attention</h2><button onClick={()=>go("all")}>View all</button></div><div className={m.list}>{data.attention.slice(0,3).map(j=><MobileJourneyRow key={j.id} journey={j} open={()=>open(j)} label={j.status==="cancellation_needed"?"Cancellation to confirm":"Booking window open"}/>)}</div></section>}<section><h2>Up next</h2><div className={m.list}>{data.bookingSoon.map(j=><MobileJourneyRow key={j.id} journey={j} booking open={()=>open(j)}/>)}{!data.bookingSoon.length&&<p className={m.emptyText}>No upcoming booking openings.</p>}</div></section><button className={m.primary} onClick={plan}>Plan a journey <ArrowRight size={17}/></button></div>;
}
/** Provides reusable phone list sections without imposing the desktop card grid. */
export function MobileScreen({title,children,action}:{title:string;children:ReactNode;action?:ReactNode}){return <div className={m.screen}><div className={m.heading}><h1>{title}</h1>{action}</div>{children}</div>;}
/** Shows a seven-day selector around the chosen date, including exact event counts. */
export function MobileWeek({date,choose,count}:{date:string;choose:(date:string)=>void;count:(date:string)=>number}){return <div className={m.week} aria-label="Calendar week">{Array.from({length:7},(_,i)=>addDays(date,i-3)).map(value=><button key={value} aria-label={`View ${value}, ${count(value)} events`} aria-pressed={value===date} onClick={()=>choose(value)}><small>{formatDay(value,{weekday:"short"})}</small><b>{Number(value.slice(-2))}</b><span aria-hidden="true">{count(value)>0?"•":" "}</span></button>)}</div>;}

/** Lists recurring travel compactly while retaining linked returns and lifecycle actions. */
export function MobileRoutines({planner,today,edit,toggle,remove}:{planner:Planner;today:string;edit:(rule?:Partial<Rule>)=>void;toggle:(rule:Rule)=>void;remove:(rule:Rule)=>void}){
  return <MobileScreen title="Routines" action={<button className={m.back} onClick={()=>edit()}>Add</button>}>{planner.rules.map(r=><article className={m.routine} key={r.id}><h2>{r.name}</h2><p>{stationLabel(r.from)} → {stationLabel(r.to)}</p><small>{r.paused?"Paused":recurrenceLabel(r)} · {formatDay(r.start)}{r.end?` — ${formatDay(r.end)}`:" · Ongoing"}</small><footer><button className={m.back} onClick={()=>edit(r)}>Edit routine</button><ActionMenu label={`Actions For ${r.name}`} actions={[{label:r.paused?"Resume Routine":"Pause Routine",onClick:()=>toggle(r)},{label:r.linkedRuleId?"Edit linked return":"Create linked return",onClick:()=>edit(planner.rules.find(other=>other.id===r.linkedRuleId)??{name:`${r.name} · return`,from:r.to,to:r.from,linkedRuleId:r.id,start:r.start>today?r.start:today,end:r.end,intervalWeeks:r.intervalWeeks,recurrence:r.recurrence})},{label:"Remove Routine",danger:true,onClick:()=>remove(r)}]}/></footer></article>)}{!planner.rules.length&&<p className={m.emptyText}>Add a routine for journeys you make regularly.</p>}</MobileScreen>;
}
/** Groups consecutive leave into expandable ranges and preserves individual removal. */
export function MobileTimeOff({planner,add,importDays,remove,breaks,plan}:{planner:Planner;add:()=>void;importDays:()=>void;remove:(id:string)=>void;breaks:{start:string;end:string;days:number;names:string[]}[];plan:(date:string)=>void}){
 return <MobileScreen title="Time off" action={<button className={m.back} onClick={add}>Add</button>}><button className={m.back} onClick={importDays}>Import holidays <ArrowRight size={16}/></button>{groupTimeOff(planner.holidays).map(group=><details className={m.routine} key={group.name+group.start}><summary><strong>{group.name}</strong><p>{formatDay(group.start)}{group.end!==group.start?` — ${formatDay(group.end)}`:""} · {group.days.length} {group.days.length===1?"day":"days"}</p></summary>{group.days.map(h=><div className={m.heading} key={h.id}><small>{formatDay(h.date)}</small><ActionMenu label={`Actions For ${h.name} on ${h.date}`} actions={[{label:"Remove time off",danger:true,onClick:()=>remove(h.id)}]}/></div>)}</details>)}{!planner.holidays.length&&<p className={m.emptyText}>Add holidays and leave to find your next longer break.</p>}<section><h2>Long weekends</h2>{breaks.map(b=><article className={m.routine} key={b.start}><h2>{b.names.join(" + ")}</h2><p>{formatDay(b.start)} — {formatDay(b.end)} · {b.days} days off</p><button className={m.back} onClick={()=>plan(b.start)}>Plan a journey <ArrowRight size={16}/></button></article>)}{!breaks.length&&<p className={m.emptyText}>No longer breaks in your current time off.</p>}</section></MobileScreen>;
}
