"use client";
import { useViewMotion } from "./view-motion";
import { useEffect,useImperativeHandle,useRef,useState,type Ref,type FormEvent } from "react";
import { ExternalLink,LogOut,Settings2,X,UserRound,SlidersHorizontal,LockKeyhole,Plug } from "lucide-react";
import { useRouter } from "next/navigation";
import { apiRequest } from "@/lib/client-api";
import type { UserProfile } from "@/lib/feature-policy";
import type { Planner } from "@/lib/travel-planner";
import { DEFAULT_TATKAL_SCHEDULE } from "@/lib/travel-planner";
import { ScheduleFields,scheduleFromForm,legacySchedule,CancellationFields,Weekdays,Field } from "./forms";
import { Toast } from "./toast";
import { BrowserPush } from "@/components/browser-push";
import { Connections } from "./connections";

import {useMobileWorkspace} from "./mobile-workspace";
import m from "./mobile-workspace.module.css";
import s from "./planner.module.css";
type Availability={emailReady:boolean;emailVerified:boolean;telegramReady:boolean;whatsappReady:boolean;googleReady:boolean};
const TABS=[{id:"profile",label:"Profile",icon:UserRound},{id:"preferences",label:"Preferences",icon:SlidersHorizontal},{id:"connections",label:"Connections",icon:Plug},{id:"security",label:"Security",icon:LockKeyhole}] as const;
/** Edits the current account profile, personal preferences, security, and configured connections. */
export function Profile({settingsRef,account,planner,onProfile,commit,fail,backup,restore,exportCalendar}:{settingsRef?:Ref<{open:()=>void}>;account:UserProfile;planner:Planner;onProfile:(user:UserProfile)=>Promise<void>;commit:(planner:Planner,message:string)=>Promise<boolean>;notice:(message:string)=>void;fail:(message:string)=>void;backup:()=>void;restore:(file?:File)=>void;exportCalendar:()=>void}){
const mobile=useMobileWorkspace();
const [available,setAvailable]=useState<Availability>();
const router=useRouter(),root=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),passwordForm=useRef<HTMLFormElement>(null),trigger=useRef<HTMLButtonElement>(null);const [telegramResult]=useState(()=>typeof window!=="undefined"?new URL(window.location.href).searchParams.get("telegram"):null);const [user,setUser]=useState(account),[menu,setMenu]=useState(false),[drawer,setDrawer]=useState(Boolean(telegramResult)),[tab,setTab]=useState<string>(telegramResult?"connections":"profile"),[busy,setBusy]=useState(false),[error,setError]=useState(telegramResult&&telegramResult!=="connected"?"Telegram authorization did not complete. Try again, or use Pair With Code.":""),[toast,setToast]=useState(telegramResult==="connected"?"Telegram connected. Send a test reminder to check delivery.":"");const policy=account.policy;const initial=Array.from(user.name.trim())[0]?.toLocaleUpperCase()??"?";
useImperativeHandle(settingsRef,()=>({open:()=>{setMenu(false);setTab(mobile?"overview":"profile");setDrawer(true);}}));
const viewMotion = useViewMotion<HTMLDivElement>(`${drawer}:${tab}`);
useEffect(()=>{let live=true;void apiRequest<Availability>("/api/railwatch/connections").then(value=>{if(live)setAvailable(value);}).catch(()=>{});return()=>{live=false;};},[account.policy,drawer]);
useEffect(()=>{if(!menu)return;const /** Dismisses the menu when a pointer event occurs outside it. */ outside=(e:PointerEvent)=>{if(!root.current?.contains(e.target as Node))setMenu(false);};const /** Closes the active menu on Escape and restores focus. */ escape=(e:KeyboardEvent)=>{if(e.key==="Escape"){setMenu(false);trigger.current?.focus();}};document.addEventListener("pointerdown",outside);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",outside);document.removeEventListener("keydown",escape);};},[menu]);
useEffect(()=>{if(drawer){dialog.current?.showModal();if(dialog.current)dialog.current.scrollTop=0;}else dialog.current?.close();},[drawer]);
useEffect(()=>{if(!telegramResult)return;const url=new URL(location.href);url.searchParams.delete("telegram");history.replaceState(null,"",url.pathname+url.search+url.hash);},[telegramResult]);
/** Routes user-settings feedback to the bottom-right toast. */
function feedback(message:string){setError("");setToast(message);}
/** Closes the active editor and clears its transient feedback. */
function close(){setToast("");dialog.current?.querySelectorAll<HTMLInputElement>('input[type="password"]').forEach(input=>{input.value="";});passwordForm.current?.reset();setError("");setDrawer(false);trigger.current?.focus();}
/** Submits the current profile or provider form and refreshes saved state. */
async function save(e:FormEvent<HTMLFormElement>,password=false){e.preventDefault();const form=e.currentTarget,fields=new FormData(form);setError("");if(password&&fields.get("newPassword")!==fields.get("confirmPassword")){setError("The new passwords do not match.");return;}setBusy(true);try{const body=password?{currentPassword:fields.get("currentPassword"),newPassword:fields.get("newPassword")}: {name:fields.get("name"),email:fields.get("email"),phoneNumber:fields.get("phoneNumber"),currentPassword:fields.get("currentPassword")};const saved=await apiRequest<UserProfile>("/api/railwatch/profile",{method:"PATCH",body:JSON.stringify(body)});setUser(saved);setAvailable(await apiRequest<Availability>("/api/railwatch/connections"));await onProfile(saved);form.reset();feedback(password?"Password changed. Other sessions have been signed out.":"Your profile has been updated.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Could not save your changes.");}finally{setBusy(false);}}
/** Saves only the current account days off, and reminder defaults. */
async function preferences(e:FormEvent<HTMLFormElement>){e.preventDefault();const fields=new FormData(e.currentTarget);setBusy(true);setError("");const weekendDays=fields.getAll("weekendDays").map(Number);if(weekendDays.length>6){setError("Keep at least one working day for long-weekend planning.");setBusy(false);return;}try{await commit({...planner,settings:{...planner.settings,weekendDays,...(policy.remindersEnabled?{bookingSchedule:scheduleFromForm(fields,"normal"),tatkalSchedule:scheduleFromForm(fields,"tatkal"),tatkalNonAcSchedule:scheduleFromForm(fields,"tatkal_non_ac"),cancellationSchedule:scheduleFromForm(fields,"cancel"),cancellationEnabled:fields.has("cancellationEnabled"),cancellationTime:String(fields.get("cancellationTime")??planner.settings.cancellationTime),quietHours:{enabled:fields.has("quietHoursEnabled"),start:String(fields.get("quietHoursStart")??"22:00"),end:String(fields.get("quietHoursEnd")??"07:00")}}:{})}},"Your preferences have been saved.");}finally{setBusy(false);}}
const activeTab=!mobile&&tab==="overview"?"profile":tab;
return <div className={s.profile} ref={root}><button ref={trigger} className={`${s.avatar} ${s.profileButton}`} aria-label="Open Profile Menu" aria-haspopup="menu" aria-expanded={menu} title={user.name} onClick={()=>setMenu(!menu)}>{initial}</button>{menu&&<div className={s.profileMenu} role="menu"><div className={s.profileIdentity}>{user.name}<small>{user.email}</small></div><button role="menuitem" onClick={()=>{setMenu(false);setError("");setTab(mobile?"overview":"profile");setDrawer(true);}}><Settings2 size={16}/>User Settings</button><a role="menuitem" href="https://www.irctc.co.in/nget/train-search" target="_blank" rel="noreferrer"><ExternalLink size={16}/>Open IRCTC</a><button role="menuitem" onClick={async()=>{try{await apiRequest("/api/auth/logout",{method:"POST"});router.replace("/login");router.refresh();}catch(e){fail(e instanceof Error?e.message:"Sign out failed.");}}}><LogOut size={16}/>Sign Out</button></div>}
<dialog className={s.profileDrawer} ref={dialog} aria-labelledby="profile-title" onCancel={close}><header><div><h2 id="profile-title">User Settings</h2><p>Your profile, preferences, and account security.</p></div><button className={s.iconButton} aria-label="Close User Settings" onClick={close}><X size={20}/></button></header><div className={s.profileLayout}>{!mobile&&<nav className={s.profileTabs} role="tablist" aria-label="User Settings Tabs" aria-orientation="horizontal">{TABS.filter(t=>t.id!=="connections"||policy.remindersEnabled||(policy.googleCalendarEnabled&&available?.googleReady)).map(t=><button key={t.id} id={"tab-"+t.id} type="button" role="tab" aria-selected={activeTab===t.id} aria-controls={"panel-"+t.id} onClick={()=>{passwordForm.current?.reset();setError("");setTab(t.id);}}><t.icon size={17}/>{t.label}</button>)}</nav>}<div ref={viewMotion} className={s.drawerBody} role="tabpanel" id={"panel-"+activeTab} aria-labelledby={mobile?undefined:"tab-"+activeTab} aria-label={mobile?activeTab:undefined}>{error&&<Toast key={error} error message={error} dismiss={()=>setError("")}/>}
{mobile&&activeTab==="overview"&&<div className={m.screen}><h3>{user.name}</h3><nav className={m.moreLinks} aria-label="Settings sections">{TABS.filter(t=>t.id!=="connections"||policy.remindersEnabled||(policy.googleCalendarEnabled&&available?.googleReady)).map(t=><button key={t.id} onClick={()=>{setError("");setTab(t.id);}}><t.icon size={20}/>{t.label}</button>)}</nav></div>}
{mobile&&activeTab!=="overview"&&<button className={m.back} onClick={()=>{passwordForm.current?.reset();setError("");setTab("overview");}}>← Settings</button>}
{activeTab==="profile"&&<form onSubmit={e=>void save(e)} key={user.name+user.email+user.phoneNumber}><h3>Personal Details</h3><p>Sign in with your email. Your username appears on your profile and dashboard.</p><div className={s.profileFields}><label className={s.field}>Username<input name="name" defaultValue={user.name} required minLength={2} maxLength={120} autoComplete="name"/></label><label className={s.field}>Email<input name="email" type="email" defaultValue={user.email} required maxLength={254} autoComplete="email"/></label><label className={s.field}>Phone Number<input name="phoneNumber" type="tel" defaultValue={user.phoneNumber} placeholder="+919876543210" maxLength={20} autoComplete="tel"/></label><label className={s.field}>Current Password<input type="password" name="currentPassword" maxLength={128} autoComplete="current-password" aria-label="Current Password"/><small>Required only when changing your email.</small></label></div>{available?.emailReady&&<div className={s.cardActions}><small>{available.emailVerified?"Email verified.":"Verify your saved email to receive booking reminders."}</small>{!available.emailVerified&&<button type="button" className={s.secondary} disabled={busy} onClick={async()=>{setBusy(true);try{await apiRequest("/api/auth/verify-email",{method:"POST",body:JSON.stringify({action:"send"})});feedback("Verification link sent to your saved email. It expires in 24 hours.");}catch(e){setError(e instanceof Error?e.message:"Could not send verification email.");}finally{setBusy(false);}}}>Verify Email</button>}</div>}<small>Your phone number is used for your WhatsApp reminders when that feature is enabled.</small><button className={s.primary} disabled={busy}>Save Profile</button></form>}
{activeTab==="preferences"&&<><form onSubmit={preferences}><h3>Personal Preferences</h3><fieldset><legend>Your Regular Days Off</legend><Weekdays weekStartsOn={planner.settings.weekStartsOn} name="weekendDays" selected={planner.settings.weekendDays}/></fieldset><p>Booking opens {policy.bookingWindowDays} days before travel. This is managed by your administrator.</p>{policy.remindersEnabled&&<><h3>Normal Booking Reminders</h3><ScheduleFields prefix="normal" initial={planner.settings.bookingSchedule??legacySchedule(planner.settings.reminderTimes,planner.settings.reminderClock)}/><details className={s.advancedConfig}><summary>Tatkal AC reminders (10 AM opening)</summary><ScheduleFields prefix="tatkal" initial={planner.settings.tatkalSchedule??DEFAULT_TATKAL_SCHEDULE}/></details><details className={s.advancedConfig}><summary>Tatkal non-AC reminders (11 AM opening)</summary><ScheduleFields prefix="tatkal_non_ac" initial={planner.settings.tatkalNonAcSchedule??DEFAULT_TATKAL_SCHEDULE.map(row=>row.daysBefore?row:{...row,time:row.time.replace("09:","10:")})}/></details><CancellationFields enabled={planner.settings.cancellationEnabled} time={planner.settings.cancellationTime} schedule={planner.settings.cancellationSchedule}/><fieldset><legend>Quiet Hours</legend><label className={s.check}><input name="quietHoursEnabled" type="checkbox" defaultChecked={planner.settings.quietHours?.enabled??false}/>Pause external reminders during quiet hours</label><div className={s.profileFields}><Field label="Start (IST)"><input type="time" name="quietHoursStart" required defaultValue={planner.settings.quietHours?.start??"22:00"}/></Field><Field label="End (IST)"><input type="time" name="quietHoursEnd" required defaultValue={planner.settings.quietHours?.end??"07:00"}/></Field></div><p className={s.help}>Email, Telegram, WhatsApp, and device notifications wait until quiet hours end, including Tatkal reminders. Your in-app inbox remains available.</p></fieldset></>}<button className={s.primary} disabled={busy}>Save Preferences</button></form><section><h3>Calendar & Backup</h3><div className={s.settingsActions}>{policy.calendarExportEnabled&&<button className={s.secondary} onClick={exportCalendar}>Export Calendar (.ics)</button>}<button className={s.secondary} onClick={backup}>Download Backup</button>{policy.ticketUploadsEnabled&&<Field label="Restore Backup"><input type="file" accept=".json,application/json" onChange={e=>{restore(e.target.files?.[0]);e.target.value="";}}/></Field>}</div></section></>}
{activeTab==="connections"&&<>{policy.remindersEnabled&&<BrowserPush notice={feedback} fail={setError}/>}<Connections planner={planner} commit={commit} notice={feedback} fail={setError} policy={policy}/></>}
{activeTab==="security"&&<form ref={passwordForm} onSubmit={e=>void save(e,true)}><h3>Change Password</h3><p>Changing your password signs out your other sessions.</p><label className={s.field}>Current Password<input type="password" name="currentPassword" required maxLength={128} autoComplete="current-password"/></label><div className={s.profileFields}><label className={s.field}>New Password<input type="password" name="newPassword" required minLength={12} maxLength={128} autoComplete="new-password"/></label><label className={s.field}>Confirm New Password<input type="password" name="confirmPassword" required minLength={12} maxLength={128} autoComplete="new-password"/></label></div><small>Use at least 12 characters with uppercase, lowercase, number, and symbol.</small><button className={s.primary} disabled={busy}>Change Password</button><button type="button" className={s.textButton} disabled={busy} onClick={async()=>{setBusy(true);setError("");try{await apiRequest("/api/auth/forgot-password",{method:"POST",body:JSON.stringify({email:user.email})});feedback("If email delivery is configured, a password reset link will be sent.");}catch(e){setError(e instanceof Error?e.message:"Could not request a reset.");}finally{setBusy(false);}}}>Forgot Your Current Password?</button></form>}
</div></div>{drawer&&toast&&!error&&<Toast key={toast} message={toast} dismiss={()=>setToast("")}/>}</dialog></div>;
}
